## Project information
site_name: Workshop estate GIS 2021 UNIPD
site_url: https://github.com/gbvitrano/workshop-estate-gis-2021#piattaforme-e-software
site_description: Workshop estate GIS 2021 UNIPD
site_author: Salvatorew Fiandaca

## Repository
repo_name: workshop-estate-gis-2021
repo_url: https://github.com/gbvitrano/workshop-estate-gis-2021#piattaforme-e-software
edit_uri: edit/main/docs/ #disables edit button

# Copyright
copyright: <a href="https://twitter.com/gbvitrano" title="@gbvitrano " target="_blank">By @gbvitrano </a> | <a href="https://creativecommons.org/licenses/by-sa/4.0/!" title="Se non specificato diversamente, tutti i contenuti sono soggetti alla licenza Creative Commons Attribution-ShareAlike 4.0 licence (CC BY-SA)" target="_blank" class="link-dark text-decoration-none">Licenza CC-BY-SA-4.0</a>

## Social Media
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/solid/home
      link: https://materialmkdocs-gb.readthedocs.io/
      name: Home Page
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/opendatasicilia
      name: account twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/opendatasicilia/
      name: gruppo facebook
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gbvitrano/MaterialMkDocs-gb
      name: Repoisitory GitHub
    - icon: fontawesome/brands/telegram
      link: http://twitter.com/opendatasicilia
      name: gruppo Telegram
    - icon: fontawesome/solid/envelope
      link: https://groups.google.com/forum/#!forum/opendatasicilia
      name: mailing list OpenDataSicilia
    - icon: fontawesome/solid/rss
      link: ../feed_rss_created.xml
      name: Feed RSS
    - icon: fontawesome/solid/file-pdf
      link: ../MaterialMkDocs-gb.pdf
      name: Scarica il file PDF
  analytics:
    provider: google
    property: UA-122084242-1
    
# Configuration
theme:
  name: material
  custom_dir: docs/overrides/
  static_templates:
    - 404.html
  language: it
  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Lato
    code: Roboto Mono
  favicon: imgs/favicon.ico
  icon:
 # logo: img/gb_128.png

plugins:
- search
- mkdocstrings
- autolinks
- macros   
# - img2fig 
- print-site:
    add_to_navigation: false
    print_page_title: 'Manuale pdf'
    add_print_site_banner: true
    print_site_banner_template: "docs/pdf/banner.tpl"
    # Table of contents
    add_table_of_contents: true
    toc_title: 'MaterialMkDocs formato PDF'
    toc_depth: 6
    # Content-related
    add_full_urls: true
    enumerate_headings: true
    enumerate_figures: true
    add_cover_page: true
    cover_page_template: "docs/pdf/cover_page.tpl"
    path_to_pdf: "MaterialMkDocs-gb.pdf"
    exclude:
    
- rss:
    abstract_chars_count: 160
    date_from_meta:
        as_creation: "date"
        as_update: false 
        datetime_format: "%d-%m-%Y"
    # datetime_format: "%Y-%m-%d"
    image: https://materialmkdocs-gb.readthedocs.io/it/latest/img/hfc_rss.png
    feed_ttl: 1440
    length: 20
    pretty_print: false
    match_path: ".*"
    url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"    

markdown_extensions:
- toc:
        permalink: ↵
- meta        
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- def_list
- abbr
- pymdownx.snippets
- footnotes

## Custom theme additions
extra_javascript:
   - stylesheets/extra.js
 
extra_css:
   - stylesheets/gbextra.css
  
## Page tree
nav:
    - Home: index.md
    - Salvatore Fiandaca: workshop_tfiandaca.md
    
   
  